version: '3.8'

services:
  arma3server:
    image: timelf123/arma3:latest
    ports:
      - "${ARMA_PORT}:${ARMA_PORT}/udp"
      - "$((ARMA_PORT+1)):$((ARMA_PORT+1))/udp"
      - "$((ARMA_PORT+2)):$((ARMA_PORT+2))/udp"
      - "$((ARMA_PORT+3)):$((ARMA_PORT+3))/udp"
    volumes:
      - ./configs:/arma3/configs
      - ./mpmissions:/arma3/mpmissions
      - ./mods:/arma3/mods
      - ./servermods:/arma3/servermods
    environment:
      - STEAM_USER=${STEAM_USER}
      - STEAM_PASSWORD=${STEAM_PASSWORD}
      - ARMA_CONFIG=server.cfg
      - ARMA_PROFILE=server
      - ARMA_WORLD=Tanoa
      - PORT=${ARMA_PORT}
      - HEADLESS_CLIENTS=${HEADLESS_CLIENTS}
      - MODS_PRESET=mods.html
    restart: unless-stopped
